
---===Error===---
Time = 16.01.2017 00:00:00Traceback (most recent call last):
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(date[0])
TypeError: arguments did not match any overloaded call:
  QListWidgetItem(QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(str, QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(QIcon, str, QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(QListWidgetItem): argument 1 has unexpected type 'datetime.date'

---===Error===---
Time = 16.01.2017 00:00:02Traceback (most recent call last):
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(date[0])
TypeError: arguments did not match any overloaded call:
  QListWidgetItem(QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(str, QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(QIcon, str, QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(QListWidgetItem): argument 1 has unexpected type 'datetime.date'

---===Error===---
Time = 16.01.2017 00:00:05Traceback (most recent call last):
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:\Users\Meller\Desktop\CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(date[0])
TypeError: arguments did not match any overloaded call:
  QListWidgetItem(QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(str, QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(QIcon, str, QListWidget parent=None, int type=QListWidgetItem.Type): argument 1 has unexpected type 'datetime.date'
  QListWidgetItem(QListWidgetItem): argument 1 has unexpected type 'datetime.date'

---===Error===---
Time = 16.01.2017 00:02:24Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(date[0].date.strftime("%d.%m.%Y"))
AttributeError: 'datetime.date' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 00:02:26Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(date[0].date.strftime("%d.%m.%Y"))
AttributeError: 'datetime.date' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 00:03:03Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(str(date[0].date.strftime("%d.%m.%Y")))
AttributeError: 'datetime.date' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 00:03:13Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 378, in set_sql_salary_date
    date = QListWidgetItem(str(date[0].date.strftime("%d.%m.%Y")))
AttributeError: 'datetime.date' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 00:03:46Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 379, in set_sql_salary_date
    self.lw_date_salarysetCurrentItem(date)
AttributeError: 'SalaryHistory' object has no attribute 'lw_date_salarysetCurrentItem'

---===Error===---
Time = 16.01.2017 00:03:47Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 231, in ui_view_history_date
    self.history = SalaryHistory()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 369, in __init__
    self.set_sql_salary_date()
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 379, in set_sql_salary_date
    self.lw_date_salarysetCurrentItem(date)
AttributeError: 'SalaryHistory' object has no attribute 'lw_date_salarysetCurrentItem'

---===Error===---
Time = 16.01.2017 18:16:38Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 238, in ui_view_history_date
    print(self.date)
AttributeError: 'SalaryList' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 18:16:42Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 238, in ui_view_history_date
    print(self.date)
AttributeError: 'SalaryList' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 18:16:51Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 238, in ui_view_history_date
    print(self.date)
AttributeError: 'SalaryList' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 18:16:58Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 238, in ui_view_history_date
    print(self.date)
AttributeError: 'SalaryList' object has no attribute 'date'

---===Error===---
Time = 16.01.2017 18:59:01Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 375, in ui_view_history_date
    for row, salary in enumerate(self.salary):
AttributeError: 'SalaryList' object has no attribute 'salary'

---===Error===---
Time = 16.01.2017 18:59:03Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 375, in ui_view_history_date
    for row, salary in enumerate(self.salary):
AttributeError: 'SalaryList' object has no attribute 'salary'

---===Error===---
Time = 16.01.2017 18:59:30Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 375, in ui_view_history_date
    for row, salary in enumerate(self.salary):
AttributeError: 'SalaryList' object has no attribute 'salary'

---===Error===---
Time = 16.01.2017 18:59:48Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 375, in ui_view_history_date
    for row, salary in enumerate(self.salary):
AttributeError: 'SalaryList' object has no attribute 'salary'

---===Error===---
Time = 16.01.2017 19:10:11Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 375, in ui_view_history_date
    for row, salary in enumerate(self.salary):
AttributeError: 'SalaryList' object has no attribute 'salary'

---===Error===---
Time = 16.01.2017 19:10:13Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 375, in ui_view_history_date
    for row, salary in enumerate(self.salary):
AttributeError: 'SalaryList' object has no attribute 'salary'

---===Error===---
Time = 16.01.2017 19:11:04Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 378, in ui_view_history_date
    new_table_item = QTableWidgetItem(str(salary_history["worker_name"]))
TypeError: 'type' object is not subscriptable

---===Error===---
Time = 17.01.2017 14:41:38Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 491, in ui_calc_many
    self.tw_many.insertRow(row)
AttributeError: 'SalaryList' object has no attribute 'tw_many'

---===Error===---
Time = 17.01.2017 14:41:38Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 491, in ui_calc_many
    self.tw_many.insertRow(row)
AttributeError: 'SalaryList' object has no attribute 'tw_many'

---===Error===---
Time = 17.01.2017 14:41:39Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 491, in ui_calc_many
    self.tw_many.insertRow(row)
AttributeError: 'SalaryList' object has no attribute 'tw_many'

---===Error===---
Time = 17.01.2017 14:41:43Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 491, in ui_calc_many
    self.tw_many.insertRow(row)
AttributeError: 'SalaryList' object has no attribute 'tw_many'

---===Error===---
Time = 17.01.2017 14:41:44Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 491, in ui_calc_many
    self.tw_many.insertRow(row)
AttributeError: 'SalaryList' object has no attribute 'tw_many'

---===Error===---
Time = 17.01.2017 14:41:44Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 491, in ui_calc_many
    self.tw_many.insertRow(row)
AttributeError: 'SalaryList' object has no attribute 'tw_many'

---===Error===---
Time = 17.01.2017 14:48:19Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:20Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:21Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:21Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:22Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:22Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:22Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:22Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:22Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:22Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:23Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:48:26Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.verticalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:49:38Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.horizontalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:50:07Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_workers.horizontalHeaderItem(0).setText("sdsdsds")
AttributeError: 'SalaryList' object has no attribute 'tw_workers'

---===Error===---
Time = 17.01.2017 14:50:37Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_many.horizontalHeaderItem(col).setText(str(operation[1]))
AttributeError: 'NoneType' object has no attribute 'setText'

---===Error===---
Time = 17.01.2017 15:30:15Traceback (most recent call last):
  File "C:/Users/Meller/Desktop/CRM-Avi\form\salary.py", line 495, in ui_calc_many
    self.tw_many.horizontalHeaderItem(col).setText(operation[0])
AttributeError: 'NoneType' object has no attribute 'setText'

---===Error===---
Time = 07.02.2017 01:07:03Traceback (most recent call last):
  File "C:/Users/Alexandr/Desktop/CRM-Avi\form\salary.py", line 553, in ui_export_salary
    to_excel.table_to_excel(self.tw_main_salary_history)
  File "C:/Users/Alexandr/Desktop/CRM-Avi\function\to_excel.py", line 12, in table_to_excel
    for col in table.rowCount():
TypeError: 'int' object is not iterable

---===Error===---
Time = 07.02.2017 01:07:38Traceback (most recent call last):
  File "C:/Users/Alexandr/Desktop/CRM-Avi\form\salary.py", line 553, in ui_export_salary
    to_excel.table_to_excel(self.tw_main_salary_history)
  File "C:/Users/Alexandr/Desktop/CRM-Avi\function\to_excel.py", line 12, in table_to_excel
    for col in table.rowCount():
TypeError: 'int' object is not iterable
